# Generated by Django 5.0.3 on 2025-07-27 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happ', '0012_alter_journalentry_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='family_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='happ.familymember'),
        ),
    ]
