# Generated by Django 5.0.3 on 2025-07-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happ', '0013_journalentry_family_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
